#!/usr/bin/env python2

from __future__ import division

import os
import pygame
import random

if os.getenv('sdlttf'):
    import draw_sdlttf as draw
else:
    import draw_cairo as draw

from editor import Editor
from insert_mode import InsertMode


class Vimim(object):
    def __init__(self):
        self.window = draw.Window()
        self.window.start = self.start
        self.window.draw = self.draw
        self.window.react = self.react
        self.window.draw_terminal = draw.draw_terminal
        self.editor = Editor(self.window)
        self.mode = InsertMode(self)

    def run(self):
        w = 800   # TODO
        h = 600
        self.window.run(w, h, 'vimim', bool(os.getenv('FULLSCREEN')))

    def start(self):
        pygame.key.set_repeat(500, 30)

    def draw(self, ctx):
        self.mode.draw(ctx)

    def react(self, event):
        if event.type == pygame.QUIT:
            self.window.running = False
            return
        if event.type == pygame.KEYDOWN:
            print repr(event.unicode)
            self.mode.keydown(event)


if __name__ == '__main__':
    Vimim().run()
