#!/usr/bin/env python2

from __future__ import division

import os
import random

if os.getenv('sdlttf'):
    import draw_sdlttf as draw
else:
    import draw_cairo as draw





def draw_test(ctx):
    colors = [0, 0.25, 0.5, 0.75, 1]
    draw.draw_terminal(window, ctx,
        [[chr(random.randint(32, 126)) for x in xrange(80)] for y in xrange(25)],
#        [[(random.random(),random.random(),random.random()) for x in xrange(80)] for y in xrange(25)])
        [[(random.choice(colors),random.choice(colors),random.choice(colors)) for x in xrange(80)] for y in xrange(25)])

if __name__ == '__main__':
    window = draw.Window()
#    window.fps = 50
    window.draw = draw_test
    window.run(800, 600, 'vimim', fullscreen=bool(os.getenv('FULLSCREEN')))
